[Icon Theme]
Name=Hicolor
Hidden=true
Directories=16x16/status,16x16@2/status,22x22/status,22x22@2/status,scalable/actions

[16x16/status]
Context=Status
Type=Fixed
Size=16

[16x16@2/status]
Context=Status
Type=Fixed
Size=16
Scale=2

[22x22/status]
Context=Status
Type=Fixed
Size=22

[22x22@2/status]
Context=Status
Type=Fixed
Size=22
Scale=2

[scalable/actions]
Context=Actions
Type=Scalable
MinSize=8
Size=16
MaxSize=512
